# coding: utf-8

"""
    Swagger Parkspot2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: test@test.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2002_user import InlineResponse2002User  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2002User(unittest.TestCase):
    """InlineResponse2002User unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002User(self):
        """Test InlineResponse2002User"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2002_user.InlineResponse2002User()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
