# coding: utf-8

"""
    Swagger Parkspot2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: test@test.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.user_api import UserApi  # noqa: E501
from swagger_client.rest import ApiException


class TestUserApi(unittest.TestCase):
    """UserApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.user_api.UserApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_user(self):
        """Test case for add_user

        Add a new user to the system  # noqa: E501
        """
        pass

    def test_delete_user(self):
        """Test case for delete_user

        Delete a user  # noqa: E501
        """
        pass

    def test_get_user_by_id(self):
        """Test case for get_user_by_id

        Get an existing user by ID  # noqa: E501
        """
        pass

    def test_get_users(self):
        """Test case for get_users

        Get existing users list  # noqa: E501
        """
        pass

    def test_modify_user(self):
        """Test case for modify_user

        Modify an existing user  # noqa: E501
        """
        pass

    def test_user_login(self):
        """Test case for user_login

        Logs user into the system  # noqa: E501
        """
        pass

    def test_user_register(self):
        """Test case for user_register

        Allows a guest to register in the system  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
