# coding: utf-8

"""
    Swagger Parkspot2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: test@test.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.new_parkspot_data import NewParkspotData  # noqa: E501
from swagger_client.rest import ApiException


class TestNewParkspotData(unittest.TestCase):
    """NewParkspotData unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNewParkspotData(self):
        """Test NewParkspotData"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.new_parkspot_data.NewParkspotData()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
