# coding: utf-8

"""
    Swagger Parkspot2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: test@test.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.parkspotdata_api import ParkspotdataApi  # noqa: E501
from swagger_client.rest import ApiException


class TestParkspotdataApi(unittest.TestCase):
    """ParkspotdataApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.parkspotdata_api.ParkspotdataApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_parkspotnode(self):
        """Test case for create_parkspotnode

        Create a new parkspot node  # noqa: E501
        """
        pass

    def test_delete_parkspot_node(self):
        """Test case for delete_parkspot_node

        Delete a parkspot node  # noqa: E501
        """
        pass

    def test_get_parkspot_node_by_id(self):
        """Test case for get_parkspot_node_by_id

        Get an existing parkspot node by ID  # noqa: E501
        """
        pass

    def test_get_parkspotnodes(self):
        """Test case for get_parkspotnodes

        Get the list of user's parkspot nodes  # noqa: E501
        """
        pass

    def test_update_parkspotnodes_status(self):
        """Test case for update_parkspotnodes_status

        Update parkspot node's status to the cloud  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
