# coding: utf-8

"""
    Swagger Parkspot2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: test@test.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.prometheus_api import PrometheusApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPrometheusApi(unittest.TestCase):
    """PrometheusApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.prometheus_api.PrometheusApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_metrics(self):
        """Test case for metrics

        Prometheus endpoint  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
