# coding: utf-8

"""
    Swagger Parkspot2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: test@test.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.inline_response2003_error import InlineResponse2003Error  # noqa: E501
from swagger_client.rest import ApiException


class TestInlineResponse2003Error(unittest.TestCase):
    """InlineResponse2003Error unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2003Error(self):
        """Test InlineResponse2003Error"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.inline_response2003_error.InlineResponse2003Error()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
