# coding: utf-8

"""
    Swagger Parkspot2.0

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: test@test.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.update_parkspot_status import UpdateParkspotStatus  # noqa: E501
from swagger_client.rest import ApiException


class TestUpdateParkspotStatus(unittest.TestCase):
    """UpdateParkspotStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUpdateParkspotStatus(self):
        """Test UpdateParkspotStatus"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.update_parkspot_status.UpdateParkspotStatus()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
