# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parkspot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='parkspot.proto',
  package='parkspot',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0eparkspot.proto\x12\x08parkspot\"\x07\n\x05\x45mpty\" \n\rParkspotImage\x12\x0f\n\x07\x43ontent\x18\x01 \x01(\x0c\"a\n\x11ParkspotRectangle\x12&\n\x05start\x18\x01 \x01(\x0b\x32\x17.parkspot.ParkSpotPoint\x12$\n\x03\x65nd\x18\x02 \x01(\x0b\x32\x17.parkspot.ParkSpotPoint\"%\n\rParkSpotPoint\x12\t\n\x01X\x18\x01 \x01(\x05\x12\t\n\x01Y\x18\x02 \x01(\x05\"C\n\rBoundingBoxes\x12\x32\n\rBoundingBoxes\x18\x01 \x03(\x0b\x32\x1b.parkspot.ParkspotRectangle\"-\n\x0b\x41\x63\x63\x65ssPoint\x12\x0c\n\x04SSID\x18\x01 \x01(\t\x12\x10\n\x08Strength\x18\x02 \x01(\x05\";\n\x0c\x41\x63\x63\x65ssPoints\x12+\n\x0c\x41\x63\x63\x65ssPoints\x18\x01 \x03(\x0b\x32\x15.parkspot.AccessPoint\"B\n\x10LoginInformation\x12\x0c\n\x04SSID\x18\x01 \x01(\t\x12\x10\n\x08Password\x18\x02 \x01(\t\x12\x0e\n\x06\x41piKey\x18\x03 \x01(\t2\x91\x03\n\x08Parkspot\x12\x36\n\x08GetImage\x12\x0f.parkspot.Empty\x1a\x17.parkspot.ParkspotImage\"\x00\x12?\n\x11GetValidatedImage\x12\x0f.parkspot.Empty\x1a\x17.parkspot.ParkspotImage\"\x00\x12>\n\x10SetBoundingBoxes\x12\x17.parkspot.BoundingBoxes\x1a\x0f.parkspot.Empty\"\x00\x12*\n\x04Ping\x12\x0f.parkspot.Empty\x1a\x0f.parkspot.Empty\"\x00\x12<\n\x0fGetAccessPoints\x12\x0f.parkspot.Empty\x1a\x16.parkspot.AccessPoints\"\x00\x12\x38\n\x07\x43onnect\x12\x1a.parkspot.LoginInformation\x1a\x0f.parkspot.Empty\"\x00\x12(\n\x02Ok\x12\x0f.parkspot.Empty\x1a\x0f.parkspot.Empty\"\x00\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='parkspot.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=35,
)


_PARKSPOTIMAGE = _descriptor.Descriptor(
  name='ParkspotImage',
  full_name='parkspot.ParkspotImage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Content', full_name='parkspot.ParkspotImage.Content', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=69,
)


_PARKSPOTRECTANGLE = _descriptor.Descriptor(
  name='ParkspotRectangle',
  full_name='parkspot.ParkspotRectangle',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='start', full_name='parkspot.ParkspotRectangle.start', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='end', full_name='parkspot.ParkspotRectangle.end', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=168,
)


_PARKSPOTPOINT = _descriptor.Descriptor(
  name='ParkSpotPoint',
  full_name='parkspot.ParkSpotPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='X', full_name='parkspot.ParkSpotPoint.X', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Y', full_name='parkspot.ParkSpotPoint.Y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=207,
)


_BOUNDINGBOXES = _descriptor.Descriptor(
  name='BoundingBoxes',
  full_name='parkspot.BoundingBoxes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='BoundingBoxes', full_name='parkspot.BoundingBoxes.BoundingBoxes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=209,
  serialized_end=276,
)


_ACCESSPOINT = _descriptor.Descriptor(
  name='AccessPoint',
  full_name='parkspot.AccessPoint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SSID', full_name='parkspot.AccessPoint.SSID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Strength', full_name='parkspot.AccessPoint.Strength', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=323,
)


_ACCESSPOINTS = _descriptor.Descriptor(
  name='AccessPoints',
  full_name='parkspot.AccessPoints',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='AccessPoints', full_name='parkspot.AccessPoints.AccessPoints', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=384,
)


_LOGININFORMATION = _descriptor.Descriptor(
  name='LoginInformation',
  full_name='parkspot.LoginInformation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='SSID', full_name='parkspot.LoginInformation.SSID', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Password', full_name='parkspot.LoginInformation.Password', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ApiKey', full_name='parkspot.LoginInformation.ApiKey', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=386,
  serialized_end=452,
)

_PARKSPOTRECTANGLE.fields_by_name['start'].message_type = _PARKSPOTPOINT
_PARKSPOTRECTANGLE.fields_by_name['end'].message_type = _PARKSPOTPOINT
_BOUNDINGBOXES.fields_by_name['BoundingBoxes'].message_type = _PARKSPOTRECTANGLE
_ACCESSPOINTS.fields_by_name['AccessPoints'].message_type = _ACCESSPOINT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['ParkspotImage'] = _PARKSPOTIMAGE
DESCRIPTOR.message_types_by_name['ParkspotRectangle'] = _PARKSPOTRECTANGLE
DESCRIPTOR.message_types_by_name['ParkSpotPoint'] = _PARKSPOTPOINT
DESCRIPTOR.message_types_by_name['BoundingBoxes'] = _BOUNDINGBOXES
DESCRIPTOR.message_types_by_name['AccessPoint'] = _ACCESSPOINT
DESCRIPTOR.message_types_by_name['AccessPoints'] = _ACCESSPOINTS
DESCRIPTOR.message_types_by_name['LoginInformation'] = _LOGININFORMATION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.Empty)
  ))
_sym_db.RegisterMessage(Empty)

ParkspotImage = _reflection.GeneratedProtocolMessageType('ParkspotImage', (_message.Message,), dict(
  DESCRIPTOR = _PARKSPOTIMAGE,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.ParkspotImage)
  ))
_sym_db.RegisterMessage(ParkspotImage)

ParkspotRectangle = _reflection.GeneratedProtocolMessageType('ParkspotRectangle', (_message.Message,), dict(
  DESCRIPTOR = _PARKSPOTRECTANGLE,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.ParkspotRectangle)
  ))
_sym_db.RegisterMessage(ParkspotRectangle)

ParkSpotPoint = _reflection.GeneratedProtocolMessageType('ParkSpotPoint', (_message.Message,), dict(
  DESCRIPTOR = _PARKSPOTPOINT,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.ParkSpotPoint)
  ))
_sym_db.RegisterMessage(ParkSpotPoint)

BoundingBoxes = _reflection.GeneratedProtocolMessageType('BoundingBoxes', (_message.Message,), dict(
  DESCRIPTOR = _BOUNDINGBOXES,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.BoundingBoxes)
  ))
_sym_db.RegisterMessage(BoundingBoxes)

AccessPoint = _reflection.GeneratedProtocolMessageType('AccessPoint', (_message.Message,), dict(
  DESCRIPTOR = _ACCESSPOINT,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.AccessPoint)
  ))
_sym_db.RegisterMessage(AccessPoint)

AccessPoints = _reflection.GeneratedProtocolMessageType('AccessPoints', (_message.Message,), dict(
  DESCRIPTOR = _ACCESSPOINTS,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.AccessPoints)
  ))
_sym_db.RegisterMessage(AccessPoints)

LoginInformation = _reflection.GeneratedProtocolMessageType('LoginInformation', (_message.Message,), dict(
  DESCRIPTOR = _LOGININFORMATION,
  __module__ = 'parkspot_pb2'
  # @@protoc_insertion_point(class_scope:parkspot.LoginInformation)
  ))
_sym_db.RegisterMessage(LoginInformation)



_PARKSPOT = _descriptor.ServiceDescriptor(
  name='Parkspot',
  full_name='parkspot.Parkspot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=455,
  serialized_end=856,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetImage',
    full_name='parkspot.Parkspot.GetImage',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PARKSPOTIMAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetValidatedImage',
    full_name='parkspot.Parkspot.GetValidatedImage',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_PARKSPOTIMAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetBoundingBoxes',
    full_name='parkspot.Parkspot.SetBoundingBoxes',
    index=2,
    containing_service=None,
    input_type=_BOUNDINGBOXES,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ping',
    full_name='parkspot.Parkspot.Ping',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetAccessPoints',
    full_name='parkspot.Parkspot.GetAccessPoints',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_ACCESSPOINTS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Connect',
    full_name='parkspot.Parkspot.Connect',
    index=5,
    containing_service=None,
    input_type=_LOGININFORMATION,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Ok',
    full_name='parkspot.Parkspot.Ok',
    index=6,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARKSPOT)

DESCRIPTOR.services_by_name['Parkspot'] = _PARKSPOT

# @@protoc_insertion_point(module_scope)
